// Generated by delombok at Mon Jul 16 22:06:49 EDT 2018
package denniskuczynski.builder;

public class Car {
    private int wheels;

    @java.lang.SuppressWarnings("all")
    Car(final int wheels) {
        this.wheels = wheels;
    }


    @java.lang.SuppressWarnings("all")
    public static class CarBuilder {
        @java.lang.SuppressWarnings("all")
        private int wheels;

        @java.lang.SuppressWarnings("all")
        CarBuilder() {
        }

        @java.lang.SuppressWarnings("all")
        public CarBuilder wheels(final int wheels) {
            this.wheels = wheels;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Car build() {
            return new Car(wheels);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Car.CarBuilder(wheels=" + this.wheels + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static CarBuilder builder() {
        return new CarBuilder();
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Car(wheels=" + this.wheels + ")";
    }
}
