// Generated by delombok at Mon Jul 16 21:49:00 EDT 2018
package denniskuczynski.superbuilder;

public abstract class Animal {
    private int legs;


    @java.lang.SuppressWarnings("all")
    public static abstract class AnimalBuilder<C extends Animal, B extends AnimalBuilder<C, B>> {
        @java.lang.SuppressWarnings("all")
        private int legs;

        @java.lang.SuppressWarnings("all")
        protected abstract B self();

        @java.lang.SuppressWarnings("all")
        public abstract C build();

        @java.lang.SuppressWarnings("all")
        public B legs(final int legs) {
            this.legs = legs;
            return self();
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Animal.AnimalBuilder(legs=" + this.legs + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    protected Animal(final AnimalBuilder<?, ?> b) {
        this.legs = b.legs;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Animal(legs=" + this.legs + ")";
    }
}
